apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.therapist.name }}
  labels:
    app: {{ .Values.therapist.name }}
spec:
  replicas: {{ .Values.therapist.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.therapist.name }}
    spec:
      containers:
        - name: {{ .Values.therapist.name }}
          image: "{{ .Values.therapist.image.repository }}:{{ .Values.therapist.image.tag }}"
          imagePullPolicy: {{ .Values.therapist.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Values.therapist.name }}
          ports:
            - containerPort: {{ .Values.therapist.image.internalPort }}