apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.area.name }}
  labels:
    app: {{ .Values.area.name }}
spec:
  replicas: {{ .Values.area.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.area.name }}
    spec:
      containers:
        - name: {{ .Values.area.name }}
          image: "{{ .Values.area.image.repository }}:{{ .Values.area.image.tag }}"
          imagePullPolicy: {{ .Values.area.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Values.area.name }}
          ports:
            - containerPort: {{ .Values.area.image.internalPort }}