{{- if index .Values "area" "enabled" }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.area.name }}
  labels:
    app: {{ .Values.area.name }}
spec:
  replicas: {{ .Values.area.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.area.name }}
    spec:
      containers:
        - name: {{ .Values.area.name }}
          image: "{{ .Values.area.image.repository }}:{{ .Values.area.image.tag }}"
          imagePullPolicy: {{ .Values.area.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Values.area.name }}
          ports:
            - containerPort: {{ .Values.area.image.internalPort }}
          readinessProbe:
            httpGet:
              path: /api/therapist-areas
              port: {{ .Values.area.image.internalPort }}
            initialDelaySeconds: {{ .Values.area.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.area.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.area.readinessProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.area.readinessProbe.timeoutSeconds }}
          livenessProbe:
            httpGet:
              path: /api/therapist-areas
              port: {{ .Values.area.image.internalPort }}
            initialDelaySeconds: {{ .Values.area.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.area.livenessProbe.periodSeconds }}
            failureThreshold: 1
            timeoutSeconds: {{ .Values.area.livenessProbe.timeoutSeconds }}
{{- end }}