apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: area
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/affinity: "cookie"
#    kubernetes.io/ingress.global-static-ip-name: area-ingress-ip
spec:
  backend:
    serviceName: therapist-area
    servicePort: 80
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: therapist-area
              servicePort: 80
#          - path: /*
#            backend:
#              serviceName: example-site-svc
#              servicePort: 8080