apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.area.name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  backend:
    serviceName: {{ .Values.area.name }}
    servicePort: {{ .Values.area.service.externalPort }}
  rules:
    - http:
        paths:
          - path: {{ .Values.area.ingress.path }}
            backend:
              serviceName: {{ .Values.area.name }}
              servicePort: {{ .Values.area.service.externalPort }}