apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: therapist
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  backend:
    serviceName: therapist
    servicePort: 80
  rules:
    - http:
        paths:
          - path: {{ .Values.therapist.ingress.path }}
            backend:
              serviceName: therapist
              servicePort: 80