apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.therapist.name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  backend:
    serviceName: {{ .Values.therapist.name }}
    servicePort: {{ .Values.therapist.service.externalPort }}
  rules:
    - http:
        paths:
          - path: {{ .Values.therapist.ingress.path }}
            backend:
              serviceName: {{ .Values.therapist.name }}
              servicePort: {{ .Values.therapist.service.externalPort }}