apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.therapist.name }}
  labels:
    app: {{ .Values.therapist.name }}
spec:
  type: {{ .Values.therapist.service.type }}
  ports:
    - port: {{ .Values.therapist.service.externalPort }}
      targetPort: {{ .Values.therapist.image.internalPort }}
#      name: therapist
  selector:
    app: {{ .Values.therapist.name }}