apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.area.name }}
  labels:
    app: {{ .Values.area.name }}
spec:
  type: {{ .Values.area.service.type }}
  ports:
    - port: {{ .Values.area.service.externalPort }}
      targetPort: {{ .Values.area.image.internalPort }}
#      name: therapist-area
  selector:
    app: {{ .Values.area.name }}