apiVersion: v1
kind: Service
metadata:
  name: therapist
  labels:
    app: therapist
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8081
#      name: therapist
  selector:
    app: therapist