apiVersion: v1
kind: Service
metadata:
  name: therapist-area
  labels:
    app: therapist
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8082
#      name: therapist-area
  selector:
    app: therapist-area