language: go
dist: xenial
sudo: required
services:
  - docker
node_js:
  - "10"
go:
  - '1.11.x'

jobs:
  include:
    - stage: test
      name: "Minikube Helm chart with Postman tests"
      env:
        - CHANGE_MINIKUBE_NONE_USER=true
        - KUBERNETES_VERSION=v1.14.0
        - NAMESPACE=mr
      install:
        - sudo apt-get update
        - sudo apt-get install -y socat
        - npm install newman
      before_script:
        # Print build info that binary is compiled with.
        - node --version
        - npm --version
        - node_modules/.bin/newman --version
        - sudo mount --make-rshared /
        - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBERNETES_VERSION}/bin/linux/amd64/kubectl
        - sudo chmod +x kubectl && sudo mv kubectl /usr/local/bin/
        # Download and install KinD
        - go get sigs.k8s.io/kind
        - kind create cluster
        # Set KUBECONFIG environment variable
        - export KUBECONFIG="$(kind get kubeconfig-path)"
        # Wait for nodes are running
        - JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done
        # Wait for Nginx Ingress controller is running
        - until kubectl -n kube-system get pods -lapp.kubernetes.io/name=nginx-ingress-controller -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1;echo "waiting for nginx ingress to be available"; kubectl get pods --all-namespaces; done
        - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get > get_helm.sh
        - chmod 700 get_helm.sh
        - ./get_helm.sh
      script:
        - helm init --wait
        # Install helm charts
        - pushd helm/massagerelax
        - helm dependency update
        - popd
        - helm install --name massagerelax helm/massagerelax --namespace ${NAMESPACE}
        # Wait for pods are being ready
        - JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl -n ${NAMESPACE} get pods -lapp=therapist -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1;echo "waiting for therapist to be available"; kubectl get pods --all-namespaces; done
        # - until kubectl -n ${NAMESPACE} get pods -lapp=area -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1;echo "waiting for area to be available"; kubectl get pods --all-namespaces; done
        - curl https://raw.githubusercontent.com/mmuller88/massagerelax-therapist/master/test/therapist.postman_collection.json > therapist.postman_collection.json
        # - node_modules/.bin/newman run therapist.postman_collection.json --global-var "host=localhost" --global-var "port=80" --global-var "prefix=/therapist/api" --global-var "protocol=http"

before_install:
  # troubleshooting info in case of problems
  - docker version
  - docker info
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_TAG
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_BUILD_NUMBER
  - echo $TRAVIS_REPO_SLUG
