dist: trusty
sudo: required
language: java
jdk:
  - oraclejdk8
services:
  - docker

matrix:
  include:
  - name: "Docker Compose Test"
    before_install:
      - docker-compose config
      - echo "Starting Massagereleax in Docker containers"
      - docker-compose ps
      - docker-compose pull
      - docker-compose up -d
      - WAIT_INTERVAL=1
        COUNTER=0
        TIMEOUT=300
        t0=`date +%s`

        echo "Waiting for massagerelax area to start"
        response=$(curl --write-out %{http_code} --output /dev/null --silent http://localhost:8082/api/therapist-areas)
        until [ "200" -eq "$response" ] || [ "$COUNTER" -eq "$TIMEOUT" ]; do
          printf '.'
          sleep $WAIT_INTERVAL
          COUNTER=$(($COUNTER+$WAIT_INTERVAL))
          response=$(curl --write-out %{http_code} --output /dev/null --silent http://localhost:8082/api/therapist-areas)
        done

        if (("$COUNTER" < "$TIMEOUT")) ; then
          t1=`date +%s`
          delta=$((($t1 - $t0)/60))
          echo "Area started in $delta minutes"
        else
          echo "Waited $COUNTER seconds"
          echo "Area could not start in time."
          echo "The last response code from /api/therapist-areas was $response"
          exit 1
        fi
    script: travis_wait 30

install: true

before_install:
  # troubleshooting info in case of problems
  - docker version
  - docker info
  - docker-compose --version
