# Note: ...
name: massagerelax
version: 0.0.1
appVersion: 0.0.1-SNAPSHOT
description: A Helm chart for deploying Massagerelax
keywords:
- massage
home: https://www.martin--mueller.com
sources:
- https://github.com/mmuller88/therapist-deployment
#icon: https://
