# This is a YAML-formatted file.  Declare variables to be passed into your templates.

# ACS will be created in a k8s cluster with a minimum of 16GB memory to split among below nodes:
# 2 x repository, 1 x share, 1 x transformers (pdfrenderer, imagemagick, libreoffice, tika) and 1 x postgresql

# Limit container memory and assign X percentage to JVM.  There are couple of ways to allocate JVM Memory for ACS Containers
# For example: 'JAVA_OPTS: "$JAVA_OPTS -XX:+PrintFlagsFinal -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"'
# But, as per Oracle docs (https://docs.oracle.com/javase/9/gctuning/parallel-collector1.htm#JSGCT-GUID-CAB83393-3438-44ED-98F0-D15641B43C7D)
# If container memory is not explicitly set, then the above flags will default max heap to 1/4th of container's memory which may not be ideal.
# Hence, setting up explicit Container memory and then assigning a percentage of it to the JVM for performance tuning.

area:
  ingress:
    path: /area

therapist:
  ingress:
    path: /therapist

mysql:
  replicaCount: 1
  ## If true, install the mysql chart.
  # Note: Set this to false if you use an external database.
  enabled: true
  nameOverride: mysql
  imageTag: "5.7.14"
  mysqlUser: massagerelax
  mysqlPassword: massagerelax
  mysqlDatabase: massagerelax
  mysqlRootPassword: massagerelax
#  persistence:
#    existingClaim: "massagerelax-volume-claim"
#    subPath: "massagerelax/database-data"
#  resources:
#    requests:
#      memory: "1500Mi"
#    limits:
#      memory: "1500Mi"